FROM rockylinux:8

RUN dnf install -y gcc gcc-c++ make curl ca-certificates git rpm-build rpmdevtools && \
    dnf clean all

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- -y --default-toolchain stable --profile minimal

ENV PATH="/root/.cargo/bin:$PATH"

# Pre-create the RPM build tree
RUN rpmdev-setuptree
